"""Initial migration

Revision ID: 086f80c73e7a
Revises: 
Create Date: 2024-12-28 20:19:39.434355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '086f80c73e7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('version_table')
    op.alter_column('article_authors', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('article_authors', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('article_tags', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('article_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('articles', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('articles_articles__fk', 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('comments', 'content',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('comments', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key('articles_articles__fk', 'articles', 'users', ['owner_id'], ['id'])
    op.alter_column('articles', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('article_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('article_tags', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('article_authors', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('article_authors', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('version_table',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='version_table_pkc')
    )
    # ### end Alembic commands ###
